    <main class="row justify-content-center">
        
        <form action="<?=$_SESSION['client']->rota_raiz?>/reservas/procuracadastro" method="post" class="col-sm-8 col-md-6 px-5">
        <h5 class="my-5">Faça sua reserva</h5>
            <div>
                <input type="email" class="input-text mb-2" name="email" required placeholder="Digite seu e-mail:">
            </div>
            <div>
                <input type="submit" value="Prosseguir" class="btn btn-success mt-2">
            </div>
        </form>
    </main>
    
</body>
</html>