    <main>        
        <h2 class="text-center my-5">Sua reserva foi feita!</h2>
        <h5 class="text-center mb-3">Detalhes da reserva:</h5>
        <?php 
            $data = explode('-', $_POST['data']);
        ?>
        <p class="text-center ">Data: <strong><?= $data[2].'/'.$data[1].'/'.$data[0] ?></strong></p>
        <p class="text-center ">Horário: <strong><?= $_POST['horario'] ?></strong></p>
        <p class="text-center ">Número de pessoas: <strong><?= $_POST['qtdPessoas'] ?></strong></p>
        <?php if($_POST['observacao'] != '') {?>
            <p class="text-center ">Observação: <strong><?= $_POST['observacao'] ?></strong></p>
        <?php }?>  
        <div class="d-flex justify-content-center">
            <a href="<?=$_SESSION['client']->rota_raiz?>/reservas/inicio" class="btn btn-primary">
                Nova reserva
            </a>
        </div>
    </main>
    
</body>
</html>