<div class="p-1">

    <section class="px-3">

        <h3 class="text-center my-3">Média de avaliação dos seus produtos</h3>

        <form class="border-bottom row mx-1 p-2">
            <div class="col-12">
                <p class="d-block">Filtros</p>
            </div>
            <div class="col-lg-6">
                <label>Grupo:</label>
                <select class="form-control">
                    <option value="">Todos</option>
                    <option value="">Entradas</option>
                    <option value="">Saladas</option>
                    <option value="">Especiais da casa</option>
                </select>
            </div>
            <div class="col-lg-6">
            <label>Produto:</label>
                <select class="form-control">
                    <option value="">Todos</option>
                    <option value="">Queijo Brie</option>
                    <option value="">Dadinho de Tapioca</option>
                    <option value="">Carpaccio</option>
                </select>
            </div>
            <div class="col-9 mt-1 mt-3">
                <label>Organizar por:</label>
                <select class="form-control">
                    <option value="">Mais bem avaliado</option>
                    <option value="">Menos bem avaliado</option>
                </select>
            </div>
            <div class="d-flex justify-content-end mt-2 col-3">
                <a href="#" class="align-self-end">
                    <i class="fa fa-search fa-2x text-secondary"></i>
                </a>
            </div>
        </form>

        <div class="row px-3 justify-content-around">

            <div class="col-lg-5 border-bottom p-2 mb-2">
                <h5>Risoto de ossobuco</h5>
                <p>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star-o text-warning"></i>
                    <span class="ml-2">4.5</span>
                </p>
                <p class="m-1">
                    <span>Sabor:<span>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star-o text-warning"></i>
                    <span class="ml-2">4.8</span>
                </p>
                <p class="m-1">
                    <span>Apresentacao:<span>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star-o text-warning"></i>
                    <span class="ml-2">4.5</span>
                </p>
            </div>

            <div class="col-lg-5 border-bottom p-2 mb-2">
                <h5>Parmeggiana 2 pessoas</h5>
                <p>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star-o text-warning"></i>
                    <span class="ml-2">4.6</span>
                </p>
                <p class="m-1">
                    <span>Sabor:<span>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star-o text-warning"></i>
                    <span class="ml-2">4.9</span>
                </p>
                <p class="m-1">
                    <span>Apresentacao:<span>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star-o text-warning"></i>
                    <span class="ml-2">4.2</span>
                </p>
            </div>
        </div>

        <div class="row px-3 justify-content-around mt-2">

            <div class="col-lg-5 border-bottom p-2 mb-2">
                <h5>Tranche de Salmão</h5>
                <p>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star-o text-warning"></i>
                    <span class="ml-2">4.7</span>
                </p>
                <p class="m-1">
                    <span>Sabor:<span>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star-o text-warning"></i>
                    <span class="ml-2">4.7</span>
                </p>
                <p class="m-1">
                    <span>Apresentacao:<span>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star-o text-warning"></i>
                    <span class="ml-2">4.7</span>
                </p>
            </div>

            <div class="col-lg-5 border-bottom p-2 mb-2">
                <h5>Filé Fusion</h5>
                <p>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star-o text-warning"></i>
                    <span class="ml-2">4.9</span>
                </p>
                <p class="m-1">
                    <span>Sabor:<span>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <span class="ml-2">5.0</span>
                </p>
                <p class="m-1">
                    <span>Apresentacao:<span>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star-o text-warning"></i>
                    <span class="ml-2">4.9</span>
                </p>
            </div>

        </div>

        <div class="ml-3">
            <button class="btn btn-link mb-4">1</button>
            <button class="btn btn-link mb-4">2</button>
            <button class="btn btn-link mb-4">3</button>
        </div>
    </section>

    <section class="p-3">
        <h3 class="text-center my-3">Avaliação dos seus produtos</h3>
        <form class="border-bottom row mx-1 p-2">
            <div class="col-lg-6">
                <label class="">Do dia:</label>
                <input class="form-control" type="date">
            </div>
            <div class="col-lg-6">
                <label class="">Ao dia:</label>
                <input class="form-control" type="date">
            </div>
            <div class="col mt-1">
                <label>Organizar por:</label>
                <select class="form-control">
                    <option value="">Mais recente</option>
                    <option value="">Mais antigo</option>
                    <option value="">Mais bem avaliado</option>
                    <option value="">Menos bem avaliado</option>
                </select>
            </div>
            <div class="d-flex justify-content-end mt-2 col">
                <a href="#" class="align-self-end">
                    <i class="fa fa-search fa-2x text-secondary"></i>
                </a>
            </div>
        </form>

        <div class="row px-3 justify-content-around">

            <div class="col-lg-5 border-bottom p-2 mb-2">
                <h5>Risoto de ossobuco</h5>
                <h6>Roberto Vieira</h6>                        
                <p>31/08/2020</p>
                <p class="m-1">
                    <span>Sabor:<span>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star-o text-warning"></i>
                </p>
                <p class="m-1">
                    <span>Apresentacao:<span>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star-o text-warning"></i>
                </p>
            </div>

            <div class="col-lg-5 border-bottom p-2 mb-2">
                <h5>Parmeggiana 2 pessoas</h5>
                <h6>Junior Santana</h6>                        
                <p>30/08/2020</p>
                <p class="m-1">
                    <span>Sabor:<span>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star-o text-warning"></i>
                    <i class="fa fa-star-o text-warning"></i>
                </p>
                <p class="m-1">
                    <span>Apresentacao:<span>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                </p>
            </div>
        </div>

        <div class="row px-3 justify-content-around mt-2">

            <div class="col-lg-5 border-bottom p-2 mb-2">
                <h5>Tranche de Salmão</h5>
                <h6>Fernando Meireles</h6>
                <p>29/08/2020</p>
                <p class="m-1">
                    <span>Sabor:<span>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star-o text-warning"></i>
                </p>
                <p class="m-1">
                    <span>Apresentacao:<span>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                </p>
            </div>

            <div class="col-lg-5 border-bottom p-2 mb-2">
                <h5>Filé Fusion</h5>
                <h6>Alice Souza</h6>                        
                <p>29/08/2020</p>
                <p class="m-1">
                    <span>Sabor:<span>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                </p>
                <p class="m-1">
                    <span>Apresentacao:<span>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                </p>
            </div>

        </div>

        <div class="ml-3">
            <button class="btn btn-link mb-4">1</button>
            <button class="btn btn-link mb-4">2</button>
            <button class="btn btn-link mb-4">3</button>
        </div>
    </section>
</div>