<?php 
    $_SESSION['route'] = $_SESSION['client']->rota_raiz.'/painel/dashboard'; 
?>
<section class="border-bottom p-3">
    <h4 class="text-center mt-2"> Reservas</h4>
    <h5>
        Hoje 
        <small>
            <?php 
                echo Date('d/m/Y');
            ?>
        </small>
    </h5>

    <div class="table-responsive">
        <?php if(count($reserva) > 0){?>
            <table class="table table-borderless">
                <thead>
                    <tr>
                        <th class="text-secondary">Nome</th>
                        <th class="text-secondary">N° Pessoas</th>
                        <th class="text-secondary">Horário</th>
                        <th class="text-secondary">Status</th>
                    </tr>
                </thead>
                <tbody> 
                    <?php foreach($reserva as $value){ ?>
                        <tr>
                            <td>
                                <div class="w-sp-nowrap">
                                    <?= $value->nome ?>
                                    <!-- button + detalhes -->
                                    <button style="background: none; border:none; margin: 0 0 0 0.2rem;" onclick="abrirModalDadosReserva('<?= $value->nome ?>', '<?= $value->telefone ?>', <?= $value->qtd_pessoas ?>, '<?= $value->data_reserva ?>', '<?= $value->hora_reserva ?>', '<?= $value->observacao ?>', '<?= $value->email ?>')"> 
                                    <small class="fa fa-info text-secondary"></small>
                                    </button>
                                </div>
                                <?php if(isset($value->observacao)){?>
                                    <small class="text-secondary">"<?= $value->observacao ?>"</small>
                                <?php } ?>
                            </td>
                            <td>
                                <?= $value->qtd_pessoas ?>
                            </td>
                            <td>
                                <?= $value->hora_reserva ?>
                            </td>

                            <?php //define a cor do status da reserva
                                switch($value->status_reserva){
                                    case 'RESERVADO':
                                        $statusColor = 'text-primary';
                                        break;
                                    case 'CONCLUIDO':
                                        $statusColor = 'text-success';
                                        break;
                                    case 'CANCELADO':
                                        $statusColor = 'text-danger';
                                        break;
                                }
                            ?>

                            <td class="<?= $statusColor ?>">
                                <?= $value->status_reserva ?>                                   
                            </td>                            
                        </tr>                          
                    <?php } ?>
                </tbody>
            </table>
        <?php } else { ?>
                <p class="text-secondary mt-2">Nenhuma reserva encontrada para hoje.</p>                
        <?php }?>
        <button onclick="loadPage('<?= $_SESSION['client']->rota_raiz ?>/painel/reserva');" class="mb-2 btn btn-outline-primary">Ver todas as reservas</button>
    </div>                
</section>

<section class="mt-4 border-bottom">
    <h4 class="text-center mt-2">Últimas avaliações</h4>
    <h5 class="p-2">Do estabelecimento</h5>
    <div class="row px-3 justify-content-between">
        <?php if(count($avaliacoesEstab) > 0){ ?>
            <?php foreach($avaliacoesEstab as $value){ ?>
                <div class="col-lg-5 p-2 mb-2 border-top border-bottom">
                    <p><?= $value->data_avaliacao ?></p>
                    <h6><?= $value->nome ?></h6>
                    <div class="m-1">
                        <?php for($i = 1; $i <= 5; $i++){ ?>
                            <?php if($i <= $value->nota_avaliacao){ ?>
                                <i class="fas fa-star text-warning"></i>
                            <?php } else {?>
                                <i class="fa fa-star-o text-warning"></i>
                            <?php } ?>
                        <?php } ?>
                        <span class="ml-2"><?= number_format($value->nota_avaliacao, 2) ?></span>
                    </div>
                    <?php if($value->comentario){?>
                        <p class="text-secondary">
                            "<?= $value->comentario ?>""
                        </p>
                    <?php } ?>
                </div>
            <?php } ?>
            <div class="col-12">            
                <button onclick="loadPage('<?= $_SESSION['client']->rota_raiz ?>/painel/avaliacoes/estabelecimento');" class="mb-3 btn btn-outline-primary">
                    Ver todas as avaliações do estabelecimento
                </button>
            </div>
        <?php } else {?>
            <p class="text-secondary mx-3">Seu estabelecimento ainda não possui nenhuma avaliação.</p>
        <?php } ?>
    </div>
    
</section> 
                
<section>
    <h5 class="p-2 mt-5">De produtos</h5>
    <div class="row px-3 justify-content-between">
        <?php if(count($avaliacoesPrato) > 0){ ?>
            <?php foreach($avaliacoesPrato as $value){ ?>
                <div class="col-lg-5 border-bottom p-2 mb-2 border-top border-bottom">
                    <p><?= $value->data_avaliacao ?></p>
                    <h6><?= $value->nome_item ?></h6>
                    <p><?= $value->nome_cliente ?></p>                        
                    <div class="m-1">
                        <?php for($i = 1; $i <= 5; $i++){ ?>
                            <?php if($i <= $value->nota_avaliacao){ ?>
                                <i class="fas fa-star text-warning"></i>
                            <?php } else {?>
                                <i class="fa fa-star-o text-warning"></i>
                            <?php } ?>
                        <?php } ?>
                        <span class="ml-2"><?= number_format($value->nota_avaliacao, 2) ?></span>
                    </div>
                    <?php if($value->comentario){?>
                        <p class="text-secondary">
                            "<?= $value->comentario ?>""
                        </p>
                    <?php } ?>
                </div>
            <?php } ?>
            <div class="col-12">            
                <button onclick="loadPage('<?= $_SESSION['client']->rota_raiz ?>/painel/avaliacoes/produtos');" class="mb-3 btn btn-outline-primary">
                    Ver todas as avaliações dos produtos
                </button>
            </div>
        <?php } else {?>
            <p class="text-secondary mx-3">Nenhum produto avaliado ainda.</p>
        <?php } ?>
    </div>
</section> 
        
<!--Modal de visualização dos dados da reserva. Dados virão do backend via JS-->
<section id="modal-dados-reserva" class="modal">                
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <h5>Detalhes da reserva</h5>
                <button class="close" data-dismiss="modal">x</button>
            </div>

            <div class="modal-body">
                <span>Nome:</span>
                <h5 id="dado-nome" class="mb-4"></h5>
                <p id="dado-tel"></p>
                <p id="dado-qtdPessoas"></p>
                <p id="dado-data"></p>
                <p id="dado-horario"></p>
                <p id="dado-obs" class="text-secondary"></p>
                <p id="dado-email"></p>                    
            </div>

        </div>
    </div>
</section>