<?php 
    $_SESSION['route'] = $_SESSION['client']->rota_raiz.'/painel/estabelecimento';
?>

<section class="p-2">
    <?php if(isset($_SESSION['update']) && $_SESSION['update'] === true){ ?>
        <div class="alert alert-success">
            Alterado com sucesso!
            <button class="close" data-dismiss="alert">x</button>
        </div>
    <?php } else if(isset($_SESSION['update']) && $_SESSION['update'] === false) {?>
        <div class="alert alert-danger">
            Erro ao alterar, verifique se os dados estão corretos.
            <button class="close" data-dismiss="alert">x</button>
        </div>
    <?php } ?>
    <?php if(isset($_SESSION['insert']) && $_SESSION['insert'] === true){ ?>
        <div class="alert alert-success">
            Inserido com sucesso!
            <button class="close" data-dismiss="alert">x</button>
        </div>
    <?php } else if(isset($_SESSION['insert']) && $_SESSION['insert'] === false) {?>
        <div class="alert alert-danger">
            Erro ao inserir, verifique se os dados estão corretos.
            <button class="close" data-dismiss="alert">x</button>
        </div>
    <?php } ?>
    <?php if(isset($_SESSION['delete']) && $_SESSION['delete'] === true){ ?>
        <div class="alert alert-success">
            Excluído com sucesso!
            <button class="close" data-dismiss="alert">x</button>
        </div>
    <?php } else if(isset($_SESSION['delete']) && $_SESSION['delete'] === false) {?>
        <div class="alert alert-danger">
            Erro ao excluir, se o problema persistir passe o problema para o suporte.
            <button class="close" data-dismiss="alert">x</button>
        </div>
    <?php } ?>

    <?php 
        if(isset($_SESSION['update'])){
            unset($_SESSION['update']);
        }   
        if(isset($_SESSION['insert'])){
            unset($_SESSION['insert']);
        }   
        if(isset($_SESSION['delete'])){
            unset($_SESSION['delete']);
        }   
    ?>

    <div class="border-bottom pb-4">
        <?php if($estab->foto_logo){ ?>
        <img src="../img/<?= $estab->foto_logo ?>" alt="Logo" width="130" height="130" class="rounded-circle d-block mx-auto">
        <button class="btn btn-outline-primary btn-sm d-block mr-3 mx-auto my-3" data-toggle="modal" data-target="#modal-foto">Alterar logotipo</button>
        <?php } else {?>
            <button class="btn btn-outline-primary btn-sm d-block mr-3 mx-auto my-3" data-toggle="modal" data-target="#modal-foto">Inserir logotipo</button>
        <?php } ?>

        <div class="px-4">
            <h6>Estabelecimento:</h6>            
            <h4 class=""><?= $estab->estabelecimento ?></h4>
            <form id="formSetNomeEstabelecimento" action="<?=$_SESSION['client']->rota_raiz?>/painel/item/nome/altera" method="post" class="border rounded p-3 d-none">
                <input type="hidden" value="<?= $estab->id ?>" name="id">
                <input type="hidden" value="<?= $estab->estabelecimento ?>" id="nome-atual">
                <label>Novo nome:</label>
                <input type="text" id="novo-nome" class="form-control" required minlength="4" value="<?= $estab->estabelecimento ?>" name="estabelecimento">
                <input type="submit" value="Salvar" class="btn btn-success mt-2">
            </form>
            <button id="btnOpenFormSetNome" onclick="showFormSetEstabelecimento();" class="btn btn-outline-primary btn-sm my-2">Alterar nome do estabelecimento</button>
        </div>
    </div>

    <div class="border-bottom p-4">
        <h6 class="d-block">Horários de reservas:</h6>
        <form action="<?=$_SESSION['client']->rota_raiz?>/painel/horarios/cadastra" method="post" class="row mb-3 ml-1">
            <div class="mr-2 mt-1">
                <label for="">Início:</label>
                <select name="horaInicio" id="horario-inicio" onchange="changeHorarioInicio();">
                    <?php for($h = 0; $h <= 23; $h++){ ?>
                        <?php for($m = 0; $m <= 59; $m += 15){ ?>|
                            <?php 
                                $horaReservas = str_pad($h, 2, 0, STR_PAD_LEFT) .':'. str_pad($m, 2, 0, STR_PAD_LEFT); 
                            ?>
                            <option value="<?= $horaReservas ?>">
                                <?= $horaReservas ?>
                            </option>
                        <?php } ?>
                    <?php } ?>
                </select>            
            </div>
            <div class="mr-2 mt-1">
                <label for="">Fim:</label>
                <select name="horaFim" id="horario-final" onchange="changeHorarioFim();">
                    <?php for($h = 0; $h <= 23; $h++){ ?>
                        <?php for($m = 0; $m <= 59; $m += 15){ ?>|
                            <?php 
                                $horaReservas = str_pad($h, 2, 0, STR_PAD_LEFT) .':'. str_pad($m, 2, 0, STR_PAD_LEFT); 
                            ?>
                            <option value="<?= $horaReservas ?>">
                                <?= $horaReservas ?>
                            </option>
                        <?php } ?>
                    <?php } ?>
                </select>
            </div>
            <div class="mr-2 mt-1">
                <label for="">Dia da semana:</label>
                <select name="diaSemana">
                    <option value="seg">Segunda-feira</option>
                    <option value="ter">Terça-feira</option>
                    <option value="qua">Quarta-feira</option>
                    <option value="qui">Quinta-feira</option>
                    <option value="sex">Sexta-feira</option>
                    <option value="sab">Sábado</option>
                    <option value="dom">Domingo</option>
                </select>
            </div>
            <div class="col-md-6">
                <button class="btn btn-sm btn-outline-success">
                    <i class="fa fa-plus-circle fa-lg"></i>    
                    <span>Novo horário</span>
                </button>
            </div> 
        </form>
        <div class="row justify-content-around">
            <div class="p-3 mt-2 border rounded">
                <h6>Segunda-feira:</h6>
                <?php foreach($horario as $hora){  ?>
                    <?php if($hora->dia_da_semana == 'seg'){ ?>
                        <form action="<?=$_SESSION['client']->rota_raiz?>/painel/horarios/remove" method="post" class="my-1">
                            <input type="hidden" value="<?= $hora->id ?>" name="id-horario">
                            <span class="mr-2 border-bottom p-1">
                                <?= $hora->horario_inicio ?> 
                                - 
                                <?= $hora->horario_fim ?>
                            </span>
                            <button type="submit">
                                <i class="fa fa-trash text-danger"></i>
                            </button>
                        </form>
                    <?php }  ?>
                <?php }  ?>
            </div>
            <div class="p-3 mt-2 border rounded">
                <h6>Terça-feira:</h6>
                <?php foreach($horario as $hora){  ?>
                    <?php if($hora->dia_da_semana == 'ter'){ ?>
                        <form action="<?=$_SESSION['client']->rota_raiz?>/painel/horarios/remove" method="post" class="my-1">
                            <input type="hidden" value="<?= $hora->id ?>" name="id-horario">
                            <span class="mr-2 border-bottom p-1">
                                <?= $hora->horario_inicio ?> 
                                - 
                                <?= $hora->horario_fim ?>
                            </span>
                            <button type="submit">
                                <i class="fa fa-trash text-danger"></i>
                            </button>
                        </form>
                    <?php }  ?>
                <?php }  ?>
            </div>
            <div class="p-3 mt-2 border rounded">
                <h6>Quarta-feira:</h6>
                <?php foreach($horario as $hora){  ?>
                    <?php if($hora->dia_da_semana == 'qua'){ ?>
                        <form action="<?=$_SESSION['client']->rota_raiz?>/painel/horarios/remove" method="post" class="my-1">
                            <input type="hidden" value="<?= $hora->id ?>" name="id-horario">
                            <span class="mr-2 border-bottom p-1">
                                <?= $hora->horario_inicio ?> 
                                - 
                                <?= $hora->horario_fim ?>
                            </span>
                            <button type="submit">
                                <i class="fa fa-trash text-danger"></i>
                            </button>
                        </form>
                    <?php }  ?>
                <?php }  ?>
            </div>
            <div class="p-3 mt-2 border rounded">
                <h6>Quinta-feira:</h6>
                <?php foreach($horario as $hora){  ?>
                    <?php if($hora->dia_da_semana == 'qui'){ ?>
                        <form action="<?=$_SESSION['client']->rota_raiz?>/painel/horarios/remove" method="post" class="my-1">
                            <input type="hidden" value="<?= $hora->id ?>" name="id-horario">
                            <span class="mr-1 border-bottom p-1">
                                <?= $hora->horario_inicio ?> 
                                - 
                                <?= $hora->horario_fim ?>
                            </span>
                            <button type="submit">
                                <i class="fa fa-trash text-danger"></i>
                            </button>
                        </form>
                    <?php }  ?>
                <?php }  ?>
            </div>
            <div class="p-3 mt-2 border rounded">
                <h6>Sexta-feira:</h6>
                <?php foreach($horario as $hora){  ?>
                    <?php if($hora->dia_da_semana == 'sex'){ ?>
                        <form action="<?=$_SESSION['client']->rota_raiz?>/painel/horarios/remove" method="post" class="my-1">
                            <input type="hidden" value="<?= $hora->id ?>" name="id-horario">
                            <span class="mr-1 border-bottom p-1">
                                <?= $hora->horario_inicio ?> 
                                - 
                                <?= $hora->horario_fim ?>
                            </span>
                            <button type="submit">
                                <i class="fa fa-trash text-danger"></i>
                            </button>
                        </form>
                    <?php }  ?>
                <?php }  ?>
            </div>
            <div class="p-3 mt-2 border rounded">
                <h6>Sábado:</h6>
                <?php foreach($horario as $hora){  ?>
                    <?php if($hora->dia_da_semana == 'sab'){ ?>
                        <form action="<?=$_SESSION['client']->rota_raiz?>/painel/horarios/remove" method="post" class="my-1">
                            <input type="hidden" value="<?= $hora->id ?>" name="id-horario">
                            <span class="mr-1 border-bottom p-1">
                                <?= $hora->horario_inicio ?> 
                                - 
                                <?= $hora->horario_fim ?>
                            </span>
                            <button type="submit">
                                <i class="fa fa-trash text-danger"></i>
                            </button>
                        </form>
                    <?php }  ?>
                <?php }  ?>
            </div>
            <div class="p-3 mt-2 border rounded">
                <h6>Domingo:</h6>
                <?php foreach($horario as $hora){  ?>
                    <?php if($hora->dia_da_semana == 'dom'){ ?>
                        <form action="<?=$_SESSION['client']->rota_raiz?>/painel/horarios/remove" method="post" class="my-1">
                            <input type="hidden" value="<?= $hora->id ?>" name="id-horario">
                            <span class="mr-1 border-bottom p-1">
                                <?= $hora->horario_inicio ?> 
                                - 
                                <?= $hora->horario_fim ?>
                            </span>
                            <button type="submit">
                                <i class="fa fa-trash text-danger"></i>
                            </button>
                        </form>
                    <?php }  ?>
                <?php }  ?>
            </div>
        </div>
        
    </div>

    <div class="px-2 px-md-4 py-4">
        <h6>Redes Sociais</h6>
        <form action="<?=$_SESSION['client']->rota_raiz?>/painel/item/whatsapp/altera" class="table-responsive my-3" method="post">
            <input type="hidden" value="<?= $estab->id ?>" name="id">
            <label>Whatsapp:</label>
            <div class="input-group">
                <input type="text" placeholder="Ex: (00)00000-0000" class="form-control" onkeypress="$(this).mask('(00) 00000-0000')" value="<?= $estab->whatsapp ?>" name="whatsapp" minlength="15" maxlength="15">
                <div class="input-group-append">
                    <input type="submit" value="salvar" class="btn btn-success btn-sm">
                </div>
            </div>            
        </form>
        <form action="<?=$_SESSION['client']->rota_raiz?>/painel/item/instagram/altera" class="table-responsive my-3" method="post">
            <input type="hidden" value="<?= $estab->id ?>" name="id">
            <label>Instagram:</label>
            <div class="input-group">
                <input type="text" placeholder="Ex: https://www.instagram.com/estabelecimento" class="form-control" value="<?= $estab->instagram?>" name="instagram">
                <div class="input-group-append">
                    <input type="submit" value="salvar" class="btn btn-success btn-sm">
                </div>
            </div>            
        </form>
        <form action="<?=$_SESSION['client']->rota_raiz?>/painel/item/facebook/altera" class="table-responsive my-3" method="post">
            <input type="hidden" value="<?= $estab->id ?>" name="id">
            <label>Facebook:</label>
            <div class="input-group">
                <input type="text" placeholder="Ex: https://www.facebook.com/estabelecimento" class="form-control" value="<?= $estab->facebook?>" name="facebook">
                <div class="input-group-append">
                    <input type="submit" value="salvar" class="btn btn-success btn-sm">
                </div>
            </div>            
        </form>
        <form action="<?=$_SESSION['client']->rota_raiz?>/painel/item/twitter/altera" class="table-responsive my-3" method="post">
            <input type="hidden" value="<?= $estab->id ?>" name="id">
            <label>Twitter:</label>
            <div class="input-group">
                <input type="text" placeholder="Ex: https://twitter.com/estabelecimento" class="form-control" value="<?= $estab->twitter ?>" name="twitter">
                <div class="input-group-append">
                    <input type="submit" value="salvar" class="btn btn-success btn-sm">
                </div>
            </div>            
        </form>
        <form action="<?=$_SESSION['client']->rota_raiz?>/painel/item/tripadvisor/altera" class="table-responsive my-3" method="post">
            <input type="hidden" value="<?= $estab->id ?>" name="id">
            <label>TripAdivisor:</label>
            <div class="input-group">
                <input type="text" placeholder="Ex: https://www.tripadvisor.com.br/estabelecimento.html" class="form-control" value="<?= $estab->tripAdvisor?>" name="tripadvisor">
                <div class="input-group-append">
                    <input type="submit" value="salvar" class="btn btn-success btn-sm">
                </div>
            </div>            
        </form>        
    </div>
</section>

<div id="modal-foto" class="modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                Inserir ou alterar a logotipo da empresa
                <button class="close" data-dismiss="modal">x</button>
            </div>
            <div class="modal-body">
                <?php if($estab->foto_logo){ ?>
                    <div class="d-flex justify-content-center">
                        <img src="../img/<?= $estab->foto_logo ?>" alt="Logo" width="100" heigth="100" class="rounded-circle">
                    </div>
                    <div class="py-2">
                        <small class="text-danger">Atenção! A foto atual será excluída e não poderá ser recuperada.</small>
                    </div>
                <?php } ?>
                <form action="<?=$_SESSION['client']->rota_raiz?>/painel/item/logotipo/altera" method="post" enctype="multipart/form-data">
                    <input type="hidden" value="<?= $estab->id ?>" name="id">
                    <label>Selecione a foto: <small>(Formatos: JPG, JPEG, PNG ou GIF. Máximo 2MB)</small></label>
                    <input type="file" class="form-control" name="fotoLogo" required>
                    <div class="d-flex justify-content-between py-3">
                        <button class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                        <input type="submit" value="Salvar" class="btn btn-success">
                    </div>                    
                </form>
            </div>
        </div>
    </div>
</div>