<!DOCTYPE html>
<html lang="pt-br">
<head>
    <!-- Meta tags Obrigatórias -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js"></script>

    <!-- HTML5Shiv -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="stylesheet" href="../css/login.css">

    <style>
        button{
            background: none;
            border: none;
        }
    </style>

    <title>Login</title>

</head>
<body>

    <main class="row no-gunters justify-content-center m-0 p-1">
        <h3 class="col-12 text-center pt-5 pb-3 text-secondary">@Digi<span class="text-secondary lead">Restmenu</span></h3>
        <form action="<?=$_SESSION['client']->rota_raiz?>/painel" method="post" class="border rounded col-12 col-md-8 col-lg-6 p-0 bg-white">
            <div class="border-bottom p-2 d-flex justify-content-center">
                <h6 class="align-self-center text-center">Faça o login para ter acesso as configurações.</h6>
            </div>
            <div class="p-2">
                <div class="input-group my-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text">
                            <i class="fas fa-envelope-square fa-lg"></i>
                        </span>
                    </div>
                    <input type="email" name="email" class="form-control" placeholder="E-mail" required value="<?php echo isset($_POST['email']) ? $_POST['email'] : ''?>">
                </div>
                <div class="input-group my-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text">
                            <i class="fas fa-lock fa-lg"></i>
                        </span>
                    </div>
                    <input type="password" name="password" class="form-control" placeholder="Senha" required>
                </div> 
                <?php if(isset($login) && $login === false){ ?>
                    <div class="text-danger">
                        Não foi possível fazer o login. Email e/ou senha não confere.
                    </div>
                <?php } ?>
                <button type="submit"class="btn btn-primary d-block mx-auto my-3">
                    <i class="fas fa-lock-open fa-lg"></i>
                    Login
                </button>        
            </div>
        </form>      

    </main>

    <!-- JavaScript (Opcional) -->
    <!-- jQuery primeiro, depois Popper.js, depois Bootstrap JS -->
    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <!-- Fontawesome -->
    <script src="https://kit.fontawesome.com/5d876fab93.js" crossorigin="anonymous"></script>
</body>
</html>