<!DOCTYPE html>
<html lang="pt-br">
<head>
    <!-- Meta tags Obrigatórias -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js"></script>

    <!-- HTML5Shiv -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <![endif]-->

    <!-- CSS personalizado -->
    <link rel="stylesheet" href="../css/panel.css">
    
    <!-- js -->
    <script src="../js/panel.js"></script>

    <style>
        button{
            background: none;
            border: none;
        }
    </style>

    <title>Painel do administrador</title>

</head>
<body>    
    <header class="bg-dark">
        <nav class="menu-horizontal">

            <div class="d-flex justify-content-between align-items-center">
                <div class="d-flex flex-column m-2">
                    <?php if($estab->foto_logo){ ?>
                        <img src="../img/<?= $estab->foto_logo ?>" alt="Logo" width="70" height="70" class="rounded-circle img-logo">
                    <?php } ?>
                    <button class="text-light d-flex" data-toggle="dropdown">
                            <span><?= $estab->estabelecimento ?></span>
                            <i class="fa fa-angle-down align-self-end ml-1"></i>
                    </button>
                    <div class="dropdown-menu bg-dark">
                        <a href="<?=$_SESSION['client']->rota_raiz?>/painel/logout" class="text-light ml-3">Sair</a>
                    </div>
                </div> 
                
                <div class="d-flex justify-content-end p-1" data-target="#menu-horizontal-links" data-toggle="collapse">
                    <button id="btn-toggle" class="fa fa-bars fa-lg text-light btn-bar">                        
                    </button>
                </div>
                
            </div>

            <div id="menu-horizontal-links" class="collapse border-top border-secondary">
                <button id="dashboard-horizontal" class="text-light button-menu" onclick="">
                    <i class="fa fa-chart-line"></i>
                    <span class="">Dashboard<span>
                </button>
                <button id="avaliacoes-horizontal" class="text-light button-menu" data-toggle="collapse" data-target="#submenu-avaliacao-horizontal">
                    <i class="fa fa-star"></i>
                    <span class="">Avaliações</span>
                    <i class="fa fa-angle-down"></i>
                </button>

                <div id="submenu-avaliacao-horizontal" class="collapse">
                        <a href="#" class="text-light d-block p-2 border-bottom border-secondary" onclick="loadPage('<?=$_SESSION['client']->rota_raiz?>/painel/avaliacoes/estabelecimento');">                        
                            Avaliações do estabelecimento
                        </a>
                        <a href="#" class="text-light d-block p-2" onclick="">
                            Avaliações dos produtos
                        </a>
                </div>
                
                <button id="reservas-horizontal" class="text-light button-menu" onclick="loadPage('<?=$_SESSION['client']->rota_raiz?>/painel/reserva');">
                    <i class="fa fa-chair"></i>
                    <span class="">Reservas<span>
                </button>
                <button id="configuracoes-cardapio-horizontal" class="text-light button-menu" data-toggle="collapse" data-target="#submenu-config-cardapio-horizontal">
                    <i class="fa fa-book-open"></i>
                    <span class="">Cardápio<span>
                    <i class="fa fa-angle-down"></i>
                </button>

                <div id="submenu-config-cardapio-horizontal" class="collapse">
                    <a href="#" class="text-light d-block p-2 border-bottom border-secondary" onclick="loadPage('<?=$_SESSION['client']->rota_raiz?>/painel/subgrupos');">Subgrupos do cardápio</a>
                    <a href="#" class="text-light d-block p-2 border-bottom border-secondary" onclick="loadPage('<?=$_SESSION['client']->rota_raiz?>/painel/itens');">Itens do cardápio</a>
                </div> 

                <button href="#" id="configuracoes-empresa-horizontal" class="text-light button-menu" onclick="loadPage('<?=$_SESSION['client']->rota_raiz?>/painel/estabelecimento');">
                    <i class="fas fa-hotel"></i>
                    <span class="">Empresa<span>
                </button>
            </div>
            
            
        </nav>
    </header>

    <main>

        <aside class="menu-vertical">
            <nav>
                <div class="d-flex flex-column p-2 border-bottom border-secondary">
                    <?php if($estab->foto_logo){ ?>
                        <img src="../img/<?= $estab->foto_logo ?>" alt="Logo" width="70" height="70" class="rounded-circle img-logo">
                    <?php } ?>
                    <button class="text-light d-flex" data-toggle="dropdown">
                        <span><?= $estab->estabelecimento ?></span>
                        <i class="fa fa-angle-down align-self-end ml-1"></i>
                    </button>
                    <div class="dropdown-menu bg-dark">
                        <a href="<?=$_SESSION['client']->rota_raiz?>/painel/logout" class="text-light ml-3">Sair</a>
                    </div>
                </div>
                
                <a id="dashboard-vertical" class="text-light button-menu" onclick="">
                    <i class="fa fa-chart-line"></i>
                    <span class="">Dashboard<span>
                </a>
                <a href="#" class="text-light button-menu" data-toggle="collapse" data-target="#submenu-avaliacao-vertical">
                    <i class="fa fa-star"></i>
                    <span class="">Avaliações</span>
                    <i class="fa fa-angle-down"></i>
                </a>
                <div id="submenu-avaliacao-vertical" class="collapse border-bottom border-secondary">
                        <a href="#" id="avaliacoes-estab-vertical" class="text-light d-block p-1 border-bottom border-secondary" onclick="loadPage('<?=$_SESSION['client']->rota_raiz?>/painel/avaliacoes/estabelecimento');">                        
                            Avaliações do estabelecimento
                        </a>
                        <a href="#" id="avaliacoes-prod-vetical" class="text-light d-block p-1" onclick="">
                            Avaliações dos produtos
                        </a>
                </div>
                
                <a href="#" id="reservas-vertical" class="text-light button-menu" onclick="loadPage('<?=$_SESSION['client']->rota_raiz?>/painel/reserva');">
                    <i class="fa fa-chair"></i>
                    <span class="">Reservas<span>
                </a>
                <a href="#" id="configuracoes-cardapio-vertical" class="text-light button-menu" data-toggle="collapse" data-target="#submenu-config-cardapio-vertical">
                    <i class="fa fa-book-open"></i>
                    <span class="">Cardápio<span>
                    <i class="fa fa-angle-down"></i>
                </a>

                <div id="submenu-config-cardapio-vertical" class="collapse">
                    <a href="#" id="config-subgrupo" class="text-light d-block p-1 border-bottom border-secondary" onclick="loadPage('<?=$_SESSION['client']->rota_raiz?>/painel/subgrupos');">Subgrupos do cardápio</a>
                    <a href="#" id="config-itens" class="text-light d-block p-1 border-bottom border-secondary" onclick="loadPage('<?=$_SESSION['client']->rota_raiz?>/painel/itens');">Itens do cardápio</a>
                </div>

                <a href="#" id="configuracoes-empresa-vertical" class="text-light button-menu"  onclick="loadPage('<?=$_SESSION['client']->rota_raiz?>/painel/estabelecimento');">
                    <i class="fas fa-hotel"></i>
                    <span class="">Empresa<span>
                </a>
            </nav> 
        </aside> 

        <div id="conteudo">                        
            <script>
                loadPage('<?= $_SESSION['route'] ?>');//chama o conteúdo da página
            </script>
           
        </div><!-- fim conteudo -->        

    </main>

    <!-- JavaScript (Opcional) -->
    <!-- jQuery primeiro, depois Popper.js, depois Bootstrap JS -->
    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <!-- Fontawesome -->
    <script src="https://kit.fontawesome.com/5d876fab93.js" crossorigin="anonymous"></script>
</body>
</html>