<?php 
    $_SESSION['route'] = $_SESSION['client']->rota_raiz.'/painel/reserva'; 
?>
<div class="p-1">
    <?php if(isset($_SESSION['insert']) && $_SESSION['insert'] === true){ ?>
        <div class="alert alert-success">
            Inserido com sucesso!
            <button class="close" data-dismiss="alert">x</button>
        </div>
    <?php } else if(isset($_SESSION['insert']) && $_SESSION['insert'] === false) {?>
        <div class="alert alert-danger">
            Erro ao inserir, verifique se os dados estão corretos.
            <button class="close" data-dismiss="alert">x</button>
        </div>
    <?php } ?>

    <?php 
        if(isset($_SESSION['update']) && $_SESSION['update'] === true){
    ?>            
        <div class="alert alert-success mx-3">
            <button class="close" data-dismiss="alert">x</button>
            Reserva alterada com sucesso!
        </div>
    <?php } else  if(isset($_SESSION['update']) && $_SESSION['update'] === false) { ?>
        <div class="alert alert-danger">
            <button class="close" data-dismiss="alert">x</button>
            Não foi possível fazer alteração na reserva. Verifique se os dados estão completos.
        </div>        
    <?php 
        } 
    ?>

    <?php 
        if(isset($_SESSION['delete']) && $_SESSION['delete'] === true){
    ?>            
        <div class="alert alert-success mx-3">
            <button class="close" data-dismiss="alert">x</button>
            Deletado com sucesso!
        </div>
    <?php } else  if(isset($_SESSION['delete']) && $_SESSION['delete'] === false) { ?>
        <div class="alert alert-danger">
            <button class="close" data-dismiss="alert">x</button>
            Não foi possível fazer a exclusão. Se o problema persistir, por favor, contate o suporte.
        </div>        
    <?php 
        } 
    ?>

    <?php 
        if(isset($_SESSION['insert'])){
            unset($_SESSION['insert']);
        }
        if(isset($_SESSION['update'])){
            unset($_SESSION['update']);
        }
        if(isset($_SESSION['delete'])){
            unset($_SESSION['delete']);
        }
    ?>
    
    <section class="mt-4"> 
        <div class="border-bottom ml-3 mb-3 pb-3">
            <button 
                class="btn btn-success btn-sm mb-1" 
                onclick="abrirModalAddBloqueio(              
                    '<?php echo isset($_SESSION['data']) ?  $_SESSION['data'] : Date('Y-m-d') ?>',
                    '<?= $_SESSION['client']->rota_raiz ?>/painel/reservas/buscahorarios'
                );"
            >
                <i class="fa fa-plus-circle"></i>
                <span>Adicionar bloqueio</span>
            </button>
            <?php 
                if(isset($_SESSION['data'])){
                    $bloqData = explode('-', $_SESSION['data']);
                }
            ?>
            <h6>
                Bloqueios de reserva para <?php echo isset($_SESSION['data']) ? $bloqData[2].'/'.$bloqData[1].'/'.$bloqData[0] : Date('d/m/Y'); ?>:
            </h6>
            <?php foreach($intervaloBloq as $intervalo){ ?>
                <form class="m-0" method="post" action="<?= $_SESSION['client']->rota_raiz ?>/painel/bloqueio/remove">                  
                    <div>
                        <input type="hidden" name="id_bloq" value="<?= $intervalo->id ?>">
                        <span class="mr-3">
                            <?= $intervalo->horario_inicio ?> - <?= $intervalo->horario_fim ?>
                        </span>
                        <button type="submit">
                            <i class="fa fa-trash text-danger"></i>
                        </button>
                    </div>                
                </form>
            <?php } ?>
        </div>
        <?php 
            if(isset($_SESSION['data'])){
                if(Date($_SESSION['data']) >= Date('Y-m-d')){
                    $dat = $_SESSION['data'];
                } else {
                    $dat = Date('Y-m-d');
                }
            } else {
                $dat = Date('Y-m-d');
            }
        ?>
        <button class="ml-3 mb-3 btn btn-success" onclick="abrirModalAddReserva('<?= $_SESSION['client']->rota_raiz ?>/painel/reservas/buscahorarios', '<?= $dat ?>', 'horarios-modal-add');">
            <i class="fa fa-plus-circle"></i>
            <span>Adicionar reserva</span>
        </button>
        <div class=" row mx-1 py-2">
            <div class="col-lg-4 col-8 col-md-6">
                <label class="">Data:</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text">
                            <i class="fas fa-calendar"></i>
                        </span>
                    </div>
                    <input 
                        class="form-control" type="date" name="data" 
                        value="<?php echo isset($_SESSION['data']) ? $_SESSION['data'] : Date('Y-m-d') ?>"
                        onchange="
                            loadPage('<?= $_SESSION['client']->rota_raiz ?>/painel/reserva?date=' + this.value);
                        "
                    >
                </div>                
            </div>
        </div>

        <div class="table-responsive">
            <?php if(count($reserva) > 0){?>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th colspan="2" class="text-secondary">Nome</th>
                            <th class="text-secondary">N° Pessoas</th>
                            <th class="text-secondary">Horário</th>
                            <th class="text-secondary">Status</th>
                        </tr>
                    </thead>
                    <tbody> 
                        <?php foreach($reserva as $value){ ?>
                            <tr>
                                <td colspan="2">
                                    <div class="w-sp-nowrap">
                                        <?= $value->nome ?>
                                        <!-- button + detalhes -->
                                        <button style="background: none; border:none; margin: 0 0 0 0.2rem;" onclick="abrirModalDadosReserva('<?= $value->nome ?>', '<?= $value->telefone ?>', <?= $value->qtd_pessoas ?>, '<?= $value->data_reserva ?>', '<?= $value->hora_reserva ?>', '<?= $value->observacao ?>', '<?= $value->email ?>')"> 
                                        <small class="fa fa-info text-secondary"></small>
                                        </button>
                                    </div>
                                    <?php if(isset($value->observacao)){?>
                                        <small class="text-secondary">"<?= $value->observacao ?>"</small>
                                    <?php } ?>
                                </td>
                                <td>
                                    <?= $value->qtd_pessoas ?>
                                </td>
                                <td>
                                    <?= $value->hora_reserva ?>
                                </td>

                                <?php //define a cor do status da reserva
                                    switch($value->status_reserva){
                                        case 'RESERVADO':
                                            $statusColor = 'text-primary';
                                            break;
                                        case 'CONCLUIDO':
                                            $statusColor = 'text-success';
                                            break;
                                        case 'CANCELADO':
                                            $statusColor = 'text-danger';
                                            break;
                                    }
                                ?>

                                <td class="<?= $statusColor ?>">
                                    <?= $value->status_reserva ?>                                   
                                </td>
                                <td>
                                    <?php if($value->status_reserva === 'RESERVADO'){?>
                                        <div class="d-flex">
                                            <!-- parâmetros do status nos links abaixo: CONCLUIDO (sem acento), CANCELADO e RESERVADO -->
                                            <form action="<?= $_SESSION['client']->rota_raiz ?>/painel/reserva/status" method="post">
                                                <input type="hidden" name="id" value="<?= $value->id ?>">
                                                <input type="hidden" name="status" value="CONCLUIDO">
                                                <input type="hidden" name="data" value="<?= $value->data_reserva ?>">
                                                <button type="submit" class="fa fa-check-square fa-lg ml-2 text-success"></button>
                                            </form>
                                            
                                            <?php //Separar dia, mês e ano
                                                $data = explode('/', $value->data_reserva);
                                                $dia = $data[0];
                                                $mes = $data[1];
                                                $ano = $data[2];
                                            ?>

                                            <button 
                                                class="fa fa-edit fa-lg ml-2 mb-1 text-primary"
                                                onclick="abrirModalAlteracaoReserva(
                                                    <?= $value->id ?>,
                                                    '<?= $value->nome ?>',
                                                    '<?= $value->telefone ?>',
                                                    <?= $value->qtd_pessoas ?>,
                                                    '<?= $ano.'-'.$mes.'-'.$dia ?>',
                                                    '<?= $value->hora_reserva ?>',
                                                    '<?= $value->observacao ?>',
                                                    '<?= $_SESSION['client']->rota_raiz ?>/painel/reservas/buscahorarios'
                                                )"
                                            ></button>
                                            <form action="<?= $_SESSION['client']->rota_raiz ?>/painel/reserva/status" method="post">
                                                <input type="hidden" name="id" value="<?= $value->id ?>">
                                                <input type="hidden" name="status" value="CANCELADO">
                                                <input type="hidden" name="data" value="<?= $value->data_reserva ?>">
                                                <button type="submit" class="fa fa-window-close fa-lg ml-2 text-danger"></button>
                                            </form>
                                        </div>

                                    <?php } else {?>
                                        <form action="<?= $_SESSION['client']->rota_raiz ?>/painel/reserva/status" method="post">
                                            <input type="hidden" name="id" value="<?= $value->id ?>">
                                            <input type="hidden" name="status" value="RESERVADO">
                                            <input type="hidden" name="data" value="<?= $value->data_reserva ?>">
                                            <button type="submit" class="fa fa-undo-alt fa-lg ml-2 text-secondary"></button>
                                        </form>
                                    <?php } ?>
                                </td>
                            </tr>                          
                        <?php } ?>
                    </tbody>
                </table>
            <?php } else { ?>
                    <h6 class="text-secondary p-2 mt-2">Nenhuma reserva encontrada para esta data.</h6>
            <?php }?>
        </div>                
    </section>

    <section class="modal" id="modal-add-reserva">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5>Adicionar reserva</h5>
                    <button class="close" data-dismiss="modal">x</button>
                </div>
                <div class="modal-body">
                    <form action="<?= $_SESSION['client']->rota_raiz ?>/painel/reservas/cadastra" method="post">
                        <div>
                            <label>Nome:</label>
                            <input type="text" name="add-nome" class="form-control mb-2" required minlength="3">
                        </div>
                        <div>
                            <label>Telefone:</label>
                            <input type="text" name="add-telefone" class="form-control mb-2" required onkeypress="$(this).mask('(00) 0000-00009')" minlength="14">
                        </div>
                        <div class="my-2">
                            <label for="" class="d-block">Quantidade de pessoas:</label>
                            <input type="number" name="add-qtdPessoas" min="1" value="2" class="form-control w-50" required>
                        </div>
                        <div class="my-2">
                            <label class="d-block">Data da reserva:</label>
                            <input 
                                type="date" 
                                id="data-modal-add"
                                name="add-dataReserva"
                                min="<?=Date('Y-m-d')?>" 
                                value="<?=Date('Y-m-d')?>" 
                                class="p-1 w-50"
                                required
                                onchange="getHorarios('<?=$_SESSION['client']->rota_raiz?>/painel/reservas/buscahorarios', this.value, 'horarios-modal-add');"
                            >
                        </div>
                        <div>
                            <label for="" class="d-block">Horário:</label>
                            <select name="add-horarioReserva" id="horarios-modal-add" class="custom-select w-50">                                
                                <?php foreach($horario as $hora){?>
                                    <option 
                                        value="<?= $hora ?>"
                                        <?php 
                                            foreach($bloqueio as $blo){
                                                if($hora == $blo){
                                                    echo 'disabled';
                                                }
                                            }
                                        ?>
                                    >
                                        <?= $hora ?>
                                        <?php 
                                            foreach($bloqueio as $blo){
                                                if($hora == $blo){
                                                    echo 'Indisponível';
                                                }
                                            }
                                        ?>
                                    </option>                                    
                                <?php }?>
                            </select>
                        </div>
                        <div class="my-2">
                            <label>Observação:</label>
                            <textarea name="add-observacao" class="form-control mb-2" cols="30" rows="5"></textarea>
                        </div>
                        <div class="d-flex justify-content-between">
                            <input type="submit" value="Salvar" class="btn btn-success">
                            <button class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>

    <!--Modal de visualização dos dados da reserva. Dados virão do backend via JS-->
    <section id="modal-dados-reserva" class="modal">                
        <div class="modal-dialog">
            <div class="modal-content">

                <div class="modal-header">
                    <h5>Detalhes da reserva</h5>
                    <button class="close" data-dismiss="modal">x</button>
                </div>

                <div class="modal-body">
                    <span>Nome:</span>
                    <h5 id="dado-nome"></h5>
                    <span>Telefone:</span>
                    <h6 id="dado-tel"></h6>
                    <span>Quantidade de pessoas:</span>
                    <h6 id="dado-qtdPessoas"></h6>
                    <span>Data:</span>
                    <h6 id="dado-data"></h6>
                    <span>Horário:</span>
                    <h6 id="dado-horario"></h6>
                    <span>Observação:</span>
                    <h6 id="dado-obs" class="text-secondary"></h6>
                    <span>Email:</span>
                    <h6 id="dado-email"></h6>                    
                </div>

            </div>
        </div>
    </section>

    <!-- Modal de alteração dos dados da reserva -->
    <section id="modal-alterar-reserva" class="modal">                
        <div class="modal-dialog">
            <div class="modal-content">

                <div class="modal-header">
                    <h5>Alterar reserva</h5>
                    <button class="close" data-dismiss="modal">x</button>
                </div>
                <form action="<?= $_SESSION['client']->rota_raiz ?>/painel/reserva/altera" method="post">
                    <div class="modal-body">
                        <input type="hidden" id="alterar_id" name="id">
                        <label>Nome:</label>
                        <input type="text" id="alterar-nome" minlength="3" maxlength="100" required class="form-control" name="nome">
                        <label>Telefone:</label>                    
                        <input type="text" id="telefone" onkeypress="$(this).mask('(00) 0000-00009')" minlength="14" required class="form-control" name="telefone"> 
                        <label>Número de pessoas:</label>                   
                        <input type="number" id="alterar-qtdPessoas" min="1" step="1" required class="form-control" name="qtdPessoas"> 
                        <div class="my-2">
                            <label class="d-block">Data:</label>                   
                            <input 
                                type="date" 
                                id="alterar-data"  
                                class="" 
                                name="data"
                                min="<?= Date('Y-m-d'); ?>"
                                required
                                onchange="getHorarios('<?=$_SESSION['client']->rota_raiz?>/painel/reservas/buscahorarios', this.value);"
                            > 
                        </div>  
                        <div class="my-2">
                            <label class="d-block">Horário:</label>                   
                            <select name="horario" id="alterar-horario">
                                <?php foreach($horario as $hora){?>
                                    <option 
                                            class="altHorario"
                                            value="<?= $hora ?>"
                                            <?php 
                                                foreach($bloqueio as $blo){
                                                    if($hora == $blo){
                                                        echo 'disabled';
                                                    }
                                                }
                                            ?>
                                        >
                                            <?= $hora ?>
                                            <?php 
                                                foreach($bloqueio as $blo){
                                                    if($hora == $blo){
                                                        echo 'Indisponível';
                                                    }
                                                }
                                            ?>
                                        </option> 
                                <?php }?>
                            </select> 
                        </div>   
                        <label>observação:</label>   
                        <textarea name="obs" id="alterar-observacao" cols="30" rows="5" class="form-control"></textarea>                
                    </div>
                    
                    <div class="modal-footer">
                        <input type="submit" value="Salvar" class="btn btn-success mr-auto">
                        <button data-dismiss="modal" class="btn btn-danger">Cancelar</button>
                    </div>
                </form>
            </div>
        </div>
    </section>

    <!-- Modal add bloqueio -->
    <section id="modal-add-bloqueio" class="modal">                
        <div class="modal-dialog">
            <div class="modal-content">

                <div class="modal-header">
                    <h5>Adicionar bloqueio de reservas</h5>
                    <button class="close" data-dismiss="modal">x</button>
                </div>
                <form action="<?= $_SESSION['client']->rota_raiz ?>/painel/bloqueio/cadastra" method="post">
                    <div class="modal-body">
                        <div class="my-2">
                            <label class="d-block" value="">Data:</label>                   
                            <input 
                                type="date"
                                id="bloq-data"
                                name="bloq-data"
                                required
                                min="<?= Date('Y-m-d'); ?>"
                                value="<?php echo isset($_SESSION['data']) ?  $_SESSION['data'] : Date('Y-m-d') ?>"
                                onchange="
                                    changeDateBloq(
                                        this.value, 
                                        '<?=$_SESSION['client']->rota_raiz?>/painel/reservas/buscahorarios', 
                                        'horario-inicio', 
                                        'horario-final'
                                    );
                                "
                            > 
                        </div>
                        <div class="my-2">
                            <label class="d-block">Início:</label>                   
                            <select name="horario-bloq-inicio" id="horario-inicio" onchange="changeHorarioInicio();">
                                <?php foreach($horario as $hora){?>
                                    <option 
                                            value="<?= $hora ?>"
                                            <?php 
                                                foreach($bloqueio as $blo){
                                                    if($hora == $blo){
                                                        echo 'disabled';
                                                    }
                                                }
                                            ?>
                                        >
                                            <?= $hora ?>
                                            <?php 
                                                foreach($bloqueio as $blo){
                                                    if($hora == $blo){
                                                        echo 'Indisponível';
                                                    }
                                                }
                                            ?>
                                        </option> 
                                <?php }?>
                            </select> 
                        </div>  
                        <div class="my-2">
                            <label class="d-block">Fim:</label>                   
                            <select name="horario-bloq-final" id="horario-final" onchange="changeHorarioFim();">
                                <?php foreach($horario as $hora){?>
                                    <option 
                                            value="<?= $hora ?>"
                                            <?php 
                                                foreach($bloqueio as $blo){
                                                    if($hora == $blo){
                                                        echo 'disabled';
                                                    }
                                                }
                                            ?>
                                        >
                                            <?= $hora ?>
                                            <?php 
                                                foreach($bloqueio as $blo){
                                                    if($hora == $blo){
                                                        echo 'Indisponível';
                                                    }
                                                }
                                            ?>
                                        </option> 
                                <?php }?>
                            </select> 
                        </div>   
                    </div>
                    
                    <div class="modal-footer">
                        <input type="submit" value="Salvar" class="btn btn-success mr-auto">
                        <button data-dismiss="modal" class="btn btn-danger">Cancelar</button>
                    </div>
                </form>
            </div>
        </div>
    </section>
</div>